[package]
name = "MintTestCoin"
version = "0.0.1"
upgrade_policy = "compatible"

[addresses]
# Named address for your module publisher. Replace on publish, e.g. --named-addresses MintToken=0x<account>
MintToken = "0xC0FFEE"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "main" }

[dev-addresses]
MintToken = "0xC0FFEE"
